FROM node:16 as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:16-alpine as release
COPY package*.json ./
RUN npm install --production
COPY --from=build /usr/src/app/dist ./dist

CMD ["node", "dist/main.js"]